#!/bin/bash

export CONFIG_PREFIX="ag_"

# if ! runSomethingInBill &> /dev/null; then
#   echo "Adding custom bin in path"
#   # include custon bin in path
# fi

h=($@)
# echo ${h[@]}

PATH=$PATH:~+/.bin/

# Start Server
runSomethingInBill ~+/server server.sh ${h[@]}

# Start Client
runSomethingInBill ~+/client client.sh ${h[@]}



if [ 0 -ne $? ]; then
  exit 1
fi
